# Generated by Django 4.1 on 2022-09-23 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntre2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='ciudad',
            new_name='ubicacion',
        ),
    ]
